const String MINDFULNESS_NOTIFICATIONS_KEY = 'MINDFULNESS_NOTIFICATIONS_KEY' ;
const String MINDFULNESS_ELIGIBILITY_KEY = 'MINDFULNESS_ELIGIBILITY_KEY';
const String HASHED_EMAIL_KEY = 'HASHED_EMAIL_KEY';