// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh5J_5WLnOMGEsBpu5IyZsxkwPtMV080g',
    appId: '1:49671142207:web:d4820974e2641c1d35718a',
    messagingSenderId: '49671142207',
    projectId: 'curiosity-e1f26',
    authDomain: 'curiosity-e1f26.firebaseapp.com',
    databaseURL: 'https://curiosity-e1f26.firebaseio.com',
    storageBucket: 'curiosity-e1f26.appspot.com',
    measurementId: 'G-Y7P2RNV2TN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtkCMH-w6tiVmSPcurD7sBnqbOSwpMhKw',
    appId: '1:49671142207:android:4cfacc108a0036a035718a',
    messagingSenderId: '49671142207',
    projectId: 'curiosity-e1f26',
    databaseURL: 'https://curiosity-e1f26.firebaseio.com',
    storageBucket: 'curiosity-e1f26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsrfcd7X5gj-20jKnspciIkaklG4jMtcs',
    appId: '1:49671142207:ios:662aeab921fa11e635718a',
    messagingSenderId: '49671142207',
    projectId: 'curiosity-e1f26',
    databaseURL: 'https://curiosity-e1f26.firebaseio.com',
    storageBucket: 'curiosity-e1f26.appspot.com',
    androidClientId: '49671142207-18dndk2f4se2ioj1ih73uavd7qedl25m.apps.googleusercontent.com',
    iosClientId: '49671142207-vide9t5jtqglqgumq21h359n8am4r664.apps.googleusercontent.com',
    iosBundleId: 'com.curiosity.app',
  );
}
